# Generated by Django 6.0 on 2025-12-11 05:21

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
    ]
