# Generated by Django 5.2.8 on 2025-11-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_carddefinition_current_eur'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddefinition',
            name='image_url_back',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
